Logs and statistics
teonet-co/trudp pull request #60
Opened 2020-03-16 14:58 UTC by Si1ver

Added logs and statistics for debugging client applications.

Fixed some compilation warnings related to const antness.

2020-03-16 15:19 UTC, chernikovdmitry approved these changes
Call you maybe (c)

2020-03-16 15:34 UTC, kirill-scherba commented on src/udp.c
> +        _trudpCallUdpDataReceivedCallback(recvlen);
I think we need define (#ifdef) here to exclude this function call in server (in teonet and teocli) (this call added for client only).

2020-03-16 15:35 UTC, kirill-scherba requested changes

2020-03-16 15:35 UTC, kirill-scherba commented on src/udp.c
> +        _trudpCallUdpDataSentCallback(sendlen);
I think we need define (#ifdef) here to exclude this function call in server (in teonet and teocli) (this call added for client only).

2020-03-17 12:58 UTC, kirill-scherba approved these changes

2020-03-17 12:59 UTC, merged