Fix/performance profiling
teonet-co/trudp pull request #63
Opened 2020-04-02 08:43 UTC by angelskieglazki

2020-04-02 11:36 UTC, chernikovdmitry requested changes
Extract some identical code to a function, please

2020-04-02 11:36 UTC, chernikovdmitry commented on src/trudp_channel.c
> +            }
Code like this exist in two places - here and in trudp.c:189, would much better to extract it to function

2020-04-02 11:36 UTC, chernikovdmitry commented on src/trudp.c
> +                }
Code like this exist in two places - here and in trudp_channel.c:635, would much better to extract it to function

2020-04-06 17:07 UTC, chernikovdmitry requested changes
Still some duplicated code, it may eventually change in different ways leading to hard-to-find bugs

2020-04-06 17:07 UTC, chernikovdmitry commented on src/trudp_channel.c
> +            tcd->td->channel_key = min_channel_key;
trudpRecalculateExpectedSendTime(tcd->td);

2020-04-06 17:50 UTC, kirill-scherba requested changes

2020-04-06 17:50 UTC, kirill-scherba commented on src/trudp_ev.c
> -    if((tt = (next_et != UINT64_MAX) ? next_et : trudpGetSendQueueTimeout(psd->td, ts)) != UINT32_MAX) {
???

2020-04-07 10:08 UTC, kshokhin commented on src/trudp_channel.c
> +                // }
Удалить это надо, чтобы не путало потом.

2020-04-07 10:13 UTC, closed without merging